name: main

on:
  push:
    branches:
      - '*'

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    needs: commitlint
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm ci
      - name: TypeScript Check
        run: npm run typecheck
      - name: ESLint Check
        run: npm run lint
      - name: Run Unit Tests
        run: npm run test
      - name: Build
        run: npm run npm:build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/main'
    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      tag: ${{ steps.changelog.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Prepare: Bump version and push tag'
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          skip-on-empty: 'true'
          output-file: 'false'
          git-message: 'chore(release): {version}'
          tag-prefix: 'v'
      - name: 'Prepare: Create Release on Github'
        if: ${{ steps.changelog.outputs.skipped != 'true' && steps.changelog.outputs.tag != ''}}
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: release
    if: github.ref == 'refs/heads/main' && needs.release.outputs.skipped != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch All Tags
        run: git fetch --tags
      - name: Checkout Correct Tag
        run: git checkout ${{ needs.release.outputs.tag }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run npm:build
      - name: 'Publish: Publish to NPM'
        run: npm run npm:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
